// packages/workspace-ui/src/components/conversation/WorktreeOfferCard.svelte
<script lang="ts">
  import { GitBranch as GitBranchIcon } from "@lucide/svelte";
  import { getWorkspaceContext } from "../../contexts";
  import { canDriveSession } from "../../contexts/sharing/session-drive";
  import AttentionCard from "./AttentionCard.svelte";
  import TranscriptCardAction from "./TranscriptCardAction.svelte";
  import { worktreeOfferView, type WorktreeOffer } from "./lib/worktree-offer";

  /**
   * The agent works in a worktree this session is not bound to
   * (docs/worktree-names.md, "Agent worktrees"). The host records the offer and
   * its answer, so the state here is the host's, after a reload too.
   */
  interface Props {
    offer: WorktreeOffer;
    tabId: string;
  }
  let { offer, tabId }: Props = $props();
  const session = getWorkspaceContext();
  const sess = $derived(session.sessionFor(tabId));
  const view = $derived(worktreeOfferView(offer));
  // The answer is an editor's; a member who may only read sees the offer.
  const canDrive = $derived(canDriveSession(sess?.run.serverId, sess?.id));
  let isDeciding = $state(false);

  async function decide(decision: "switch" | "keep") {
    if (isDeciding) return;
    isDeciding = true;
    try {
      await session.opening.decideWorktreeOffer(tabId, offer.id, decision);
    } finally {
      isDeciding = false;
    }
  }
</script>

<AttentionCard
  title={view.title}
  type={view.type}
  target={view.target}
  resolved={!view.canDecide}
  testId="worktree-offer-card"
>
  {#snippet icon()}<GitBranchIcon />{/snippet}
  {#snippet actions()}
    {#if view.canDecide}
      {#if !canDrive}
        <span class="text-transcript-meta text-(--muted-foreground)">Waiting for an editor</span>
      {:else}
        <TranscriptCardAction
          kind="ghost"
          disabled={isDeciding}
          data-testid="worktree-offer-keep"
          onclick={() => void decide("keep")}>Keep current</TranscriptCardAction
        >
        <TranscriptCardAction
          kind="filled"
          disabled={isDeciding}
          data-testid="worktree-offer-switch"
          onclick={() => void decide("switch")}>Switch</TranscriptCardAction
        >
      {/if}
    {/if}
  {/snippet}
  <p class="m-0 {view.failed ? 'text-destructive' : 'text-(--muted-foreground)'}">{view.detail}</p>
</AttentionCard>

// apps/mobile/src/features/threads/WorktreeOfferCard.tsx
import { useState } from "react";
import { View } from "react-native";

import { AppText as Text } from "../../components/AppText";
import type { ConversationStore } from "../conversation/conversation-store";
import type { TranscriptItem } from "../conversation/lib/transcript-model";
import { worktreeOfferText } from "../conversation/lib/worktree-offer";
import { RequestActionButton } from "./RequestActionButton";

type WorktreeOfferItem = Extract<TranscriptItem, { kind: "worktree_offer" }>;

/**
 * The agent works in a worktree this session is not bound to
 * (docs/worktree-names.md, "Agent worktrees"). It wears the approval card's chrome.
 * The state is the host's, so it is the same after a reload and on desktop.
 */
export function WorktreeOfferCard(props: { readonly store: ConversationStore; readonly offer: WorktreeOfferItem }) {
  const text = worktreeOfferText(props.offer);
  const [busy, setBusy] = useState(false);
  const decide = async (decision: "switch" | "keep") => {
    setBusy(true);
    try {
      await props.store.controller.decideWorktreeOffer(props.offer.offerId, decision);
    } finally {
      setBusy(false);
    }
  };
  return (
    <View className="mb-5 gap-2.5 rounded-[20px] border border-border bg-card-alt p-4">
      <Text className="font-t3-bold text-2xs uppercase tracking-[1.1px] text-foreground-secondary">{text.eyebrow}</Text>
      <Text className="font-t3-bold text-base text-foreground">{text.title}</Text>
      {text.detail ? (
        <Text className={text.failed ? "font-sans text-sm leading-normal text-danger" : "font-sans text-sm leading-normal text-foreground-secondary"}>
          {text.detail}
        </Text>
      ) : null}
      {text.canDecide ? (
        <View className="flex-row flex-wrap gap-2.5">
          <RequestActionButton label="Switch" tone="primary" disabled={busy} onPress={() => void decide("switch")} />
          <RequestActionButton label="Keep current" tone="secondary" disabled={busy} onPress={() => void decide("keep")} />
        </View>
      ) : null}
    </View>
  );
}
